### ISSUE TITLE
404 error when reaching '/' for static files

### ISSUE THREAD

**Issue by develaper** [chunghha/docker-go-gin#1]
Hi @chunghha ,
I would like to start saying that I really appreciate your work on this repo that saved me a lot of time and helped to go straight to the funny coding part of the proccess.
I am trying to follow a tutorial: _[Building a Web App With Go, Gin and React](https://github.com/codehakase/golang-gin)_   but I got stuck in one of the first steps just trying to display the index.html view that I have in ./views folder.
I chaged the main.go file using Static
```
package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/contrib/static"
)

func main() {

	router := gin.Default()

	router.Use(static.Serve("/home", static.LocalFile("./views", true)))

	// Setup route group for the API
  api := router.Group("/api")
  {
    api.GET("/", func(c *gin.Context) {
      c.JSON(http.StatusOK, gin.H {
        "message": "pong",
      })
    })
  }

	router.Run() // listen and serve on 0.0.0.0:8080
}
```
And also added:
```
RUN go get -u github.com/gin-gonic/gin
RUN go get -u github.com/gin-gonic/contrib/static
RUN go build -o ./app ./src/main.go

```
To the Dockerfile.

I found an issue related in the gin-gonic repository reporting the same problem:
Inability to use '/' for static files
but I couldn't figure out how to apply any of the proposed solutions.

In case that you want to check my code you can find it here:
https://github.com/develaper/docker-go-gingonic-react-tutorial/blob/master/src/main.go

Please let me know if you have any advise about how to proceed from here or if you need any other info.
Thanks for your time.

**Comment by chunghha** [comment]
Hi @develaper 
Per your code, you missed to add your "views" folder to docker like as,
![image](https://user-images.githubusercontent.com/24458075/76245470-f140b980-6209-11ea-961a-243663871f65.png)
Then you can see these with your code.
![image](https://user-images.githubusercontent.com/24458075/76245501-04ec2000-620a-11ea-8105-c7a358fb65d7.png)
![image](https://user-images.githubusercontent.com/24458075/76245522-09b0d400-620a-11ea-9435-2e21c3f4e870.png)

**Comment by develaper** [comment]
woooow! @chunghha it worked like charm. It was a newbie error. Maybe I should spend more time studying and working in my Docker skills.
Thanks for your help and for your time.
